{ title: "Tranfert", data: "TRANFERT_AVIS" },
{ title: "Hotel", data: "_AVIS" },
{ title: "Restauration", data: "_AVIS" },
{ title: "Service & Accueil", data: "_AVIS" },
{ title: "Animation", data: "_AVIS" },
{ title: "Excurstion & Guide", data: "_AVIS" },
{ title: "", data: "_AVIS" },
{ title: "", data: "_AVIS" },
{ title: "", data: "_AVIS" },
{ title: "", data: "_AVIS" },
{ title: "", data: "_AVIS" },
{ title: "", data: "_AVIS" },