INSERT INTO typevoyage (LIBELLE, DESCRIPTION) VALUES ("Circuit", ""),
    ("Séjour", ""),
    ("Croisière", "");
INSERT INTO prestation (LIBELLE, DESCRIPTION) VALUES ("TRANSFERT", ""),
    ("Hotel", ""),
    ("Restaurant", ""),
    ("Service/Accueil", ""),
    ("Animation", ""),
    ("Excursions/Guide", ""),
    ("Transport aerien", ""),
    ("Transport car", ""),
    ("Thalasso/SPA", ""),
    ("Croisiere", "");